export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL';
export const CREATE_STUDENT_RESET = 'CREATE_STUDENT_RESET';

export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL';

export const ALL_STUDENT_REQUEST = 'ALL_STUDENT_REQUEST';
export const ALL_STUDENT_SUCCESS = 'ALL_STUDENT_SUCCESS';
export const ALL_STUDENT_FAIL = 'ALL_STUDENT_FAIL';

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';
export const UPDATE_STUDENT_RESET = 'UPDATE_STUDENT_RESET';

export const UPLOAD_FILES_REQUEST = 'UPLOAD_FILES_REQUEST';
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';
export const UPLOAD_FILES_FAIL = 'UPLOAD_FILES_FAIL';

export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";